---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculator-api
  name: calculator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
    spec:
      containers:
      - image: samitkumarpatel/calculator-api:latest
        name: calculator-api
        ports:
          - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculatora-api
  name: calculatora-api
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: calculatora-api
  type: NodePort
